---
abstract: 'Interface to hide text into an image.'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  Carp::Always: 0.10
  GD::Image: 2.38
  Math::Random: 0.71
  Mouse: 0.93
  POSIX: 1.09
  Readonly: 1.03
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-Image
provides:
  Crypt::Image:
    file: lib/Crypt/Image.pm
    version: 0.02
  Crypt::Image::Axis:
    file: lib/Crypt/Image/Axis.pm
    version: 0.02
  Crypt::Image::Util:
    file: lib/Crypt/Image/Util.pm
    version: 0.02
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
