---
abstract: 'Interface to hide text into an image.'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Crypt-Image
no_index:
  directory:
    - t
    - inc
requires:
  GD::Image: '2.38'
  Math::Random: '0.71'
  Mouse: '0.93'
  POSIX: '1.09'
  Readonly: '1.03'
  Test::More: '0'
version: '0.04'
